manifest_id: id2026-02-20
created_by: Test User
created_at: '2026-02-20T09:28:53.961Z'
simulated: true
job_steps:
- step_name: Data Loader
  type: load
  enabled: true
  params:
    output_source_name: source1
    mode: discovery
    path: /data/GTEX
    include: '*.svs'
    recursive: false
    directory_mode: false
    columns:
      column_name: svs_path
      filename_to_columnname: ^(?P<slide_id>.+?)\.svs$
      header: true
      delimiter: ','
    fileType: default
    description: ''
    notes: ''
- step_name: Run Command
  type: custom_command
  command_chain_type: dicom_conversion
  chain_command_name: Convert to DICOM
  enabled: true
  params:
    input_source_name: source1
    command: wsidicomizer -i {svs_path} -o ./uploads/data/dicom_output/{slide_id}
      --source opentile --format jpeg --quality 100
    execution_mode: per_row
- step_name: Data Loader
  type: load
  command_chain_type: dicom_conversion
  chain_command_name: Convert to DICOM
  enabled: true
  params:
    output_source_name: dicom_source
    path: ./uploads/data/dicom_output
    mode: discovery
    include: '*'
    directory_mode: true
    columns:
      column_name: dicom_path
      filename_to_columnname: ^(?P<slide_id>.+)$
- step_name: Run Command
  type: custom_command
  enabled: true
  params:
    command: echo "Conversion Finished"
    execution_mode: once
    input_source_name: source1
    description: ''
    notes: ''
